# Generated by Django 3.2 on 2021-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
