# Generated by Django 3.2 on 2021-04-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zone',
            field=models.IntegerField(blank=True, choices=[(1, 'Zone One'), (2, 'Zone Two'), (3, 'Zone Three'), (4, 'Zone Four'), (5, 'Zone Five')], help_text='District Zone', null=True),
        ),
    ]
