# Generated by Django 3.2 on 2021-05-04 00:15

from django.db import migrations

def forward(apps, schema_editor):
    schools = [
    'Barbara Morgan Stem Academy',
    'Cecil D Andrus Elementary',
    'Centennial High School',
    'Central Academy High School',
    'Chaparral Elementary',
    'Chief Joseph School Of The Arts',
    'Christine Donnell School Of The Arts',
    'Crossroads Middle School',
    'Desert Sage Elementary School',
    'Discovery Elementary School',
    'Eagle Academy',
    'Eagle Elementary School Of The Arts',
    'Eagle High School',
    'Eagle Hills Elementary School',
    'Eagle Middle School',
    'Eliza Hart Spalding Stem Academy',
    'Frontier Elementary School',
    'Galileo Magnet School',
    'Heritage Middle School',
    'Hillsdale Elementary',
    'Hunter Elementary School',
    'Idaho Fine Arts Academy',
    'Joplin Elementary School',
    'Lake Hazel Elementary School',
    'Lake Hazel Middle School',
    'Lewis & Clark Middle School',
    'Lowell Scott Middle School',
    'Mary Mcpherson Elementary',
    'Mcmillan Elementary',
    'Meridian Academy',
    'Meridian Elementary School',
    'Meridian High School',
    'Meridian Medical Arts Charter',
    'Meridian Middle School',
    'Meridian Technical Charter High School',
    'Mountain View High School',
    'Paramount Elementary School',
    'Pathways Middle School',
    'Pepper Ridge Elementary',
    'Peregrine Elementary School',
    'Pioneer School Of The Arts',
    'Ponderosa Elementary School',
    'Prospect Elementary School',
    'Rebound School Of Opportunity',
    'Renaissance High School',
    'River Valley Elementary School',
    'Rocky Mountain High School',
    'Sawtooth Middle School',
    'Seven Oaks Elementary',
    'Siena Elementary',
    'Silver Sage Elementary School',
    'Star Elementary School',
    'Star Middle School',
    'Summerwind School Of Math And Science',
    'Ustick Elementary School',
    'Victory Middle School',
    'Willow Creek Elementary School',
    ]

    School = apps.get_model('app', 'School')
    for s in schools:
        School.objects.create(
            name=s,
        )
    return

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_school'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
