# Generated by Django 3.2 on 2021-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210503_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
