# Generated by Django 3.2 on 2021-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_is_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
