# Generated by Django 3.2.1 on 2021-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210506_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
