# Generated by Django 3.2.1 on 2021-05-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
