# Generated by Django 3.2.1 on 2021-05-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_voter_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='suffix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
