# Generated by Django 3.2.1 on 2021-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_voter_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
