# Generated by Django 3.2.1 on 2021-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_signage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_voter',
            field=models.BooleanField(default=False),
        ),
    ]
