# Generated by Django 3.2.2 on 2021-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210509_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Zone One'), (2, 'Zone Two'), (3, 'Zone Three'), (4, 'Zone Four')], null=True),
        ),
    ]
