# Generated by Django 3.2.2 on 2021-05-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210510_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='app.account'),
        ),
    ]
