# Generated by Django 3.2.2 on 2021-05-13 04:42

import app.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210512_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[app.models.validate_video]),
        ),
    ]
