# Generated by Django 3.2.3 on 2021-05-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
