# Generated by Django 3.2.3 on 2021-05-20 02:50

from django.db import migrations

def forward(apps, schema_editor):
    Account = apps.get_model('app', 'Account')
    accounts = Account.objects.exclude(comments='')
    for account in accounts:
        Comment.objects.create(
            account=account,
            written=account.comments,
            created=account.created,
        )
    return


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_discussion'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
