# Generated by Django 3.2.3 on 2021-05-20 03:33

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='state',
            field=django_fsm.FSMIntegerField(default=0),
        ),
    ]
