# Generated by Django 3.2.3 on 2021-05-20 03:40

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_account_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0),
        ),
    ]
