# Generated by Django 3.2.3 on 2021-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_account_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_attending',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_signage',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_speaker',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_volunteer',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
