# Generated by Django 3.2.3 on 2021-05-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210519_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_moderated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
    ]
