# Generated by Django 3.2.3 on 2021-05-20 14:20

from django.db import migrations, models

def forward(apps, schema_editor):
    Comment = apps.get_model('app', 'Comment')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(Comment)
    Comment.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('app', '0030_auto_20210519_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='Comment',
            name='polymorphic_ctype',
            field=models.ForeignKey(related_name='polymorphic_app.comment_set+', editable=False, to='contenttypes.ContentType', null=True, on_delete=models.SET_NULL),
        ),
        migrations.RunPython(forward)
    ]
