# Generated by Django 3.2.3 on 2021-05-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0031_auto_20210520_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.comment')),
                ('text', models.TextField(blank=True, default='', max_length=2000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.comment',),
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.comment_set+', to='contenttypes.contenttype'),
        ),
    ]
