# Generated by Django 3.2.3 on 2021-05-20 14:34

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210520_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='written',
        ),
        migrations.CreateModel(
            name='SpokenComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.comment')),
                ('video', models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.comment',),
        ),
    ]
