# Generated by Django 3.2.3 on 2021-05-20 19:09

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210520_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Moderated'), (0, 'New'), (10, 'Approved'), (20, 'Featured')], default=0),
        ),
    ]
