# Generated by Django 3.2.3 on 2021-05-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210521_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.account'),
        ),
    ]
