# Generated by Django 3.2.3 on 2021-05-29 16:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_comment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Moderated'), (0, 'New'), (10, 'Approved')], default=0),
        ),
    ]
