# Generated by Django 3.2.3 on 2021-05-30 12:54

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_comment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_moderated',
        ),
        migrations.AlterField(
            model_name='comment',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Denied'), (0, 'Pending'), (10, 'Approved')], default=0),
        ),
    ]
