# Generated by Django 3.2.3 on 2021-06-01 00:36

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210530_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Denied'), (-5, 'Archived'), (0, 'Pending'), (10, 'Approved')], default=0),
        ),
    ]
